# docker-compose.yml
version: "3.7"

services:
  back:
    env_file: .env
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 1337:3000
    depends_on:
      - db
      - redis
    networks:
      - coalibot.fr
      - db-network
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: coalibot
    volumes:
       - db-data:/var/lib/postgresql
    networks:
      - db-network

  redis:
    image: redis
    networks:
      - redis

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    networks:
      - coalibot.fr
    depends_on:
      - back
    ports:
      - 8080:80

volumes:
  db-data:

networks:
  db-network:
  coalibot.fr:
  redis: