# docker-compose.yml
version: "3.4"

services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./back:/back
    depends_on:
      - db
    networks:
      - coalibot.fr
    ports:
      - "127.0.0.1:${APP_PORT_HOST}:${APP_PORT_HOST}"

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
    networks:
      - coalibot.fr

volumes:
  db-data:

networks:
  coalibot.fr:
