# Generated by Django 2.2rc1 on 2019-03-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190324_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursususer',
            name='begin_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cursususer',
            name='end_at',
            field=models.DateField(null=True),
        ),
    ]
