# Generated by Django 2.2rc1 on 2019-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190324_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
